### PR TITLE
Full support for hasktags, fix compilation with GHC 8.8.1

### PR DESCRIPTION
**Pull request by arybczak**

### CODE REVIEW

**Comment by arybczak** [comment]
Hmm, looks like travis stopped working. @23Skidoo do you know why?

**Comment by 23Skidoo** [comment]
IIUC either @piotrskowron-scrive or @timtimellis revoked the Travis app's access rights to the Scrive org via my account. Perhaps we can re-enable it, but only limit its access rights to public repos?

**Comment by jonathanjouty** [comment]
I have re-enabled it and re-triggered a build to test that it can post status updates, shows up as _pending_ so I guess it worked.

**Comment by kubek2k** [comment]
@arybczak out of curiosity - what was the issue with hasktags?

**Comment by 23Skidoo** [comment]
Merged, thanks!

**Comment by 23Skidoo** [comment]
@kubek2k 
> what was the issue with hasktags?

Hasktags uses a hacky regex-based parser that apparently requires some massaging of the source code to work properly.

**Comment by kubek2k** [comment]
@23Skidoo 🙇

**Pull request merged**
